/* Generated by tools/make_sight_scenarios.py -- do not edit.
 *
 * End-to-end position-recovery truth for `sight_reduction --scenario-check`:
 * the composition sky -> corrected altitude -> multi-body fix -> position,
 * checked against external answers. Three families:
 *
 *   scenario_rows   known navigation-sphere lat/lon + instant + 2-5 bodies;
 *                   Ho = asin(obs_unit . body_unit) with body_unit the
 *                   Skyfield/DE421 APPARENT place in ITRS (the quantity our
 *                   ephemeris approximates), obs_unit the local zenith.
 *                   Surface-observer topocentric altaz is not used: it still
 *                   contains parallax already removed from the Ho consumed
 *                   by the fix (up to about a degree for the Moon).
 *                   Recovered position vs truth = the almanac error propagated
 *                   through the fix geometry.
 *   alinnman_sights two published fixes from
 *   alinnman2_sights github.com/alinnman/celestial-navigation: Chicago
 *                   two-Sun + Vega (2024-05, answer 41 deg 51'N 87 deg 39'W)
 *                   and Capella + Moon + Vega off Tunis (2024-09, answer
 *                   36 deg 45'11"N 10 deg 13'8"E). The second is a raw MOON
 *                   sight: ~40' of lunar parallax removed by our chain with
 *                   our own ephemeris HP. Raw Hs through our correction
 *                   chain then our n-body fix.
 *   intercept_rows  ~10 Sun rows (Hs -> Ho -> Hc/Zn/intercept), NA-traceable,
 *                   from github.com/rgleason/celestial_navigation_pi
 *                   (test/altitude_tests.cpp INTERCEPT_SIGHTS).
 *
 * Transcribed numbers only (no vendored code). Instants treated as UT1;
 * Sun/scenario rows carry Skyfield's TT - UT1. See the tool for full
 * provenance and the Earth-model note on the alinnman truth.
 *
 * Provenance (see tools/make_sight_scenarios.py):
 *   skyfield 1.54
 *   de421.bsp sha256
 *     a20a7139da04cbc462454634918e9a9ca69127044e2cc9d4f9c16e238d2deedc
 *   hip_main.dat sha256
 *     58ceabb104d647160d9437ce6e513a02a036bb4ad9f8879a5a22fd52943616e0 */

/* A recovery scenario: truth navigation-sphere lat/lon, an
 * instant, and up to 5 bodies with their parallax-corrected Ho.
 * body[i] is a star index 0..17, -1 for the Sun, -2 for the Moon;
 * ho_marcmin[i] = round(asin(obs_unit . body_unit) in arcminutes
 * x 1000). n < 5 rows leave the unused body/ho slots 0. two_body
 * routes the check through astro_nav_fix_two_body instead of the
 * n-body solver. */
typedef struct {
    int32_t lat_cdeg, lon_cdeg;  /* truth navigation-sphere lat/lon */
    int64_t ut1_ms;
    int32_t tt_minus_ut1_ms;     /* for any Sun/Moon body */
    int32_t n;
    int32_t two_body;            /* 1 -> use the closed-form fix */
    int32_t body[5];             /* star index 0..17, -1 Sun, -2 Moon */
    int64_t ho_marcmin[5];
} scenario_row_t;

static const scenario_row_t scenario_rows[] = {
    {   4190,   -8760,   768255600000LL,      0, 4, 0, {  17,   9,  12,   2,   0 },
      {   2483525LL,   2661844LL,   1220221LL,   2616908LL,         0LL } }, /* north-mid twilight: Polaris, Altair, Antares, Arcturus */
    {  -3390,   15120,   495666600000LL,      0, 4, 0, {   9,  14,   8,  12,   0 },
      {   2706940LL,   2324579LL,   1353577LL,   3485100LL,         0LL } }, /* south-mid twilight: Altair, Fomalhaut, Achernar, Antares */
    {    130,   10380,   259299000000LL,      0, 5, 0, {   2,  11,   1,   0,  13 },
      {   1765644LL,   2522447LL,   1032222LL,   2058261LL,   2678335LL } }, /* equatorial night: Arcturus, Spica, Canopus, Sirius, Pollux */
    {   6410,   -2190,    47480400000LL,      0, 3, 0, {  17,   9,   2,   0,   0 },
      {   3821608LL,   1950605LL,   1775294LL,         0LL,         0LL } }, /* high-north summer: Polaris, Altair, Arcturus */
    {  -5480,   -6830,   961587000000LL,      0, 4, 0, {  11,  12,   8,   1,   0 },
      {   2768500LL,   2533215LL,   1331361LL,   2212182LL,         0LL } }, /* high-south winter: Spica, Antares, Achernar, Canopus */
    {   3780,  -12240,   626200200000LL,      0, 2, 1, {  10,  14,   0,   0,   0 },
      {   1067282LL,   1352812LL,         0LL,         0LL,         0LL } }, /* mid-north two-body: Aldebaran, Fomalhaut */
    {   2130,  -15790,   376048800000LL,  66572, 3, 0, {  17,  -1,   2,   0,   0 },
      {   1239678LL,   2793305LL,   3794183LL,         0LL,         0LL } }, /* tropic sun+stars: Polaris, Sun, Arcturus */
    {   4550,   -7360,   119482200000LL,      0, 4, 0, {  16,   6,  10,  17,   0 },
      {   1773624LL,   2713625LL,   3302972LL,   2755766LL,         0LL } }, /* north-atlantic dawn: Regulus, Procyon, Aldebaran, Polaris */
    {  -2020,    5750,   860640300000LL,      0, 4, 0, {  16,   8,   7,  13,   0 },
      {   2573881LL,    925759LL,   3052009LL,   2510192LL,         0LL } }, /* indian-ocean dusk: Regulus, Achernar, Betelgeuse, Pollux */
    {   2150,  -15800,  1045626000000LL,      0, 3, 0, {   3,  12,  11,   0,   0 },
      {   2477920LL,   2250144LL,   2969057LL,         0LL,         0LL } }, /* pacific mid dawn: Vega, Antares, Spica */
    {  -3390,    1840,   191053200000LL,      0, 5, 0, {  10,   0,   1,   8,  14 },
      {   2244464LL,   2630548LL,   3267295LL,   3575207LL,   1941987LL } }, /* cape-town evening: Aldebaran, Sirius, Canopus, Achernar, Fomalhaut */
    {   6410,   -2190,   787564800000LL,      0, 4, 0, {  17,   4,   9,   3,   0 },
      {   3873197LL,   2752141LL,   1125542LL,   2218810LL,         0LL } }, /* reykjavik winter: Polaris, Capella, Altair, Vega */
    {    130,   10380,   650799000000LL,      0, 4, 0, {   4,   5,   8,  14,   0 },
      {   1706884LL,   2482864LL,   1880536LL,   2166957LL,         0LL } }, /* singapore predawn: Capella, Rigel, Achernar, Fomalhaut */
    {  -4290,   14730,   421887600000LL,      0, 4, 0, {  11,  12,   0,  16,   0 },
      {   3328128LL,   2263685LL,    928744LL,   1636667LL,         0LL } }, /* hobart night: Spica, Antares, Sirius, Regulus */
    {   3770,   -2570,    14302800000LL,      0, 3, 0, {  17,  15,  11,   0,   0 },
      {   2225616LL,   2833978LL,   1279187LL,         0LL,         0LL } }, /* azores midnight: Polaris, Deneb, Spica */
    {    890,   -7950,   559449000000LL,  68864, 3, 0, {  -1,   1,  10,   0,   0 },
      {   2943040LL,   1060491LL,   1215430LL,         0LL,         0LL } }, /* panama sun+stars: Sun, Canopus, Aldebaran */
    {   -130,    3680,   942381000000LL,      0, 4, 0, {   8,   9,   3,  15,   0 },
      {   1314818LL,   3084386LL,   1498654LL,   2304179LL,         0LL } }, /* nairobi evening: Achernar, Altair, Vega, Deneb */
    {  -3980,   -7320,   709988400000LL,      0, 4, 0, {   2,  12,   1,  16,   0 },
      {   1651840LL,   2527350LL,   1655752LL,   1602900LL,         0LL } }, /* valdivia dusk: Arcturus, Antares, Canopus, Regulus */
    {   6120,  -14990,   341697600000LL,      0, 3, 0, {  17,   4,   9,   0,   0 },
      {   3706450LL,   2867794LL,   1018906LL,         0LL,         0LL } }, /* anchorage night: Polaris, Capella, Altair */
    {   1910,    7290,  1109937600000LL,      0, 4, 0, {  17,  15,  12,  11,   0 },
      {   1110646LL,   1425101LL,   2569882LL,   2696192LL,         0LL } }, /* mumbai predawn: Polaris, Deneb, Antares, Spica */
    {  -3190,   11590,   162865800000LL,      0, 5, 0, {   6,  16,   1,   8,   7 },
      {   3051309LL,   1492961LL,   4126637LL,   1981125LL,   2927368LL } }, /* perth evening: Procyon, Regulus, Canopus, Achernar, Betelgeuse */
    {   4460,   -6360,   841524300000LL,      0, 4, 0, {   4,   5,  15,  17,   0 },
      {   4077522LL,   1823162LL,   1542098LL,   2713698LL,         0LL } }, /* halifax dawn: Capella, Rigel, Deneb, Polaris */
    {  -1810,   17840,   987886800000LL,      0, 4, 0, {  11,   1,   0,  16,   0 },
      {   3156851LL,   1673387LL,   1867430LL,   3488445LL,         0LL } }, /* suva night: Spica, Canopus, Sirius, Regulus */
    {  -5170,   -5790,   460958400000LL,  67501, 3, 0, {  11,   8,  -1,   0,   0 },
      {   1619186LL,   1835423LL,   1370930LL,         0LL,         0LL } }, /* stanley sun+stars: Spica, Achernar, Sun */
    {   3600,   -4000,   829177200000LL,  69141, 2, 1, {  -1,  -2,   0,   0,   0 },
      {   1969470LL,   1831857LL,         0LL,         0LL,         0LL } }, /* mid-atlantic sun-moon: Sun, Moon */
    {  -1600,   15200,  1033293600000LL,  69145, 2, 0, {  -1,  -2,   0,   0,   0 },
      {   2022610LL,   3579571LL,         0LL,         0LL,         0LL } }, /* coral-sea sun-moon: Sun, Moon */
    {   4550,    -400,   884718000000LL,  69075, 4, 0, {   3,   2,  -2,  17,   0 },
      {   2553249LL,   3811961LL,   1379381LL,   2694157LL,         0LL } }, /* biscay moon+stars: Vega, Arcturus, Moon, Polaris */
    {  -3800,   16000,   154303200000LL,  64668, 4, 0, {   5,   8,  14,  -2,   0 },
      {   1341862LL,   4125691LL,   4002866LL,   3253046LL,         0LL } }, /* tasman moon+stars: Rigel, Achernar, Fomalhaut, Moon */
    {   3610,    -540,   521445600000LL,  68403, 3, 0, {   3,  -2,  -1,   0,   0 },
      {   1476843LL,   3167463LL,   1083224LL,         0LL,         0LL } }, /* gibraltar sun+moon+star: Vega, Moon, Sun */
};

#define SCENARIO_ROW_COUNT (sizeof scenario_rows / sizeof scenario_rows[0])

/* alinnman published fixes: raw sextant altitude (Hs) per sight;
 * the check runs our standard-atmosphere correction chain (eye=0,
 * ie=0, limb=0, T=10 C, P=1010 mb -- exactly the corrections
 * their Sight() applied: Bennett refraction, no dip, central
 * limb) then our n-body fix. body: star index, -1 = Sun, -2 =
 * Moon. For a Moon row the C side supplies OUR ephemeris HP at
 * the instant (their Sight() looked HP up from its almanac at
 * the sight hour), so the raw sight exercises refraction + lunar
 * parallax end to end through the Moon correction chain. */
typedef struct {
    int64_t ut1_ms;
    int32_t tt_minus_ut1_ms;
    int32_t body;          /* star index, -1 = Sun, -2 = Moon */
    int64_t hs_marcmin;    /* raw sextant altitude */
} alinnman_sight_t;

static const alinnman_sight_t alinnman_sights[] = {
    {   768196518000LL,  69204,  -1,   3308018LL }, /* Sun  2024-05-05 15:55:18  55:08:01.1 */
    {   768222079000LL,  69204,  -1,   1168317LL }, /* Sun  2024-05-05 23:01:19  19:28:19.0 */
    {   768240253000LL,  69204,   3,   1816395LL }, /* Vega 2024-05-06 04:04:13  30:16:23.7 */
};

#define ALINNMAN_SIGHT_COUNT (sizeof alinnman_sights / sizeof alinnman_sights[0])
#define ALINNMAN_TRUTH_LAT_CDEG 4185 /* 41 deg 51'00.1"N (geodetic; see the tool) */
#define ALINNMAN_TRUTH_LON_CDEG -8765 /* 87 deg 39'00.2"W */
#define ALINNMAN_SEED_LAT_CDEG 4000 /* their rough DRP */
#define ALINNMAN_SEED_LON_CDEG -9000

static const alinnman_sight_t alinnman2_sights[] = {
    {   779888173000LL,  69125,   4,   1989567LL }, /* Capella 2024-09-17 23:36:13  33:09:34.0 */
    {   779888473000LL,  69125,  -2,   2902087LL }, /* Moon    2024-09-17 23:41:13  48:22:05.2 */
    {   779888773000LL,  69125,   3,   1539067LL }, /* Vega    2024-09-17 23:46:13  25:39:04.0 */
};

#define ALINNMAN2_SIGHT_COUNT (sizeof alinnman2_sights / sizeof alinnman2_sights[0])
#define ALINNMAN2_TRUTH_LAT_CDEG 3675 /* 36 deg 45'11.01"N (geodetic; see the tool) */
#define ALINNMAN2_TRUTH_LON_CDEG 1022 /* 10 deg 13'8.00"E */
#define ALINNMAN2_SEED_LAT_CDEG 3500 /* their rough DRP */
#define ALINNMAN2_SEED_LON_CDEG 1000

/* rgleason INTERCEPT_SIGHTS: a full Sun sight line. hs_marcmin the
 * raw sextant altitude; ie_marcmin NEGATIVE because their chain
 * subtracts the index error (Ha = Hs - IE - dip) while ours adds
 * it. gha/dec baked into their published Sun direction (Q2.30)
 * for the ephemeris and reduction gates. ho/hc are their published
 * observed and computed altitudes; zn their azimuth; intercept in
 * tenths of a nautical mile, POSITIVE toward. All rows: T=10 C,
 * P=1010 mb, index error 1.5', eye 3.5 m. */
typedef struct {
    int64_t ut1_ms;
    int32_t tt_minus_ut1_ms;
    int32_t limb;             /* +1 lower, -1 upper */
    int32_t temp_c, pressure_mb;
    int64_t ie_marcmin;       /* signed; negative (their convention) */
    int32_t eye_cm;
    int64_t hs_marcmin;
    int64_t ho_marcmin;       /* their published Ho */
    int32_t bx, by, bz;       /* their Sun direction, Q2.30 */
    int32_t dr_lat_cdeg, dr_lon_cdeg;
    int64_t hc_marcmin;       /* their published Hc */
    int32_t zn_cdeg;          /* their published azimuth */
    int32_t intercept_tenths_nm; /* signed; + toward */
} intercept_row_t;

static const intercept_row_t intercept_rows[] = {
    {   806287620000LL,  69127, +1, 10, 1010,     -1500LL,  350,    1800000LL,
        1809426LL,   989699287,  -177125901,   376886244,   4324,   -7753,   1810910LL,   8940,   -15 }, /* 2025-07-20 12:47:00 lower */
    {   806303793000LL,  69127, +1, 10, 1010,     -1500LL,  350,    4021000LL,
        4031604LL,   217119776,  -981942288,   376257690,   4324,   -7753,   4036569LL,  18000,   -50 }, /* 2025-07-20 17:16:33 lower */
    {   806307441000LL,  69127, +1, 10, 1010,     -1500LL,  350,    4500000LL,
        4510734LL,   -47923429, -1004570583,   376115398,    571,   -9273,   4512196LL,  35999,   -15 }, /* 2025-07-20 18:17:21 lower */
    {   806318300000LL,  69127, +1, 10, 1010,     -1500LL,  350,    2105000LL,
        2114712LL,  -747220221,  -673379479,   375690728,   4324,   -7753,   2111649LL,  26567,   +31 }, /* 2025-07-20 21:18:20 lower */
    {   806298215000LL,  69127, +1, 10, 1010,     -1500LL,  350,    1800000LL,
        1809426LL,   586925178,  -816521278,   376474889,  -1877,  -10044,   1805871LL,   5131,   +36 }, /* 2025-07-20 15:43:35 lower */
    {   795064984000LL,  69140, -1, 10, 1010,     -1500LL,  350,    2227300LL,
        2205276LL,   712361875,  -801365966,   -57224585,   4324,   -7753,   2206761LL,  14258,   -15 }, /* 2025-03-12 15:23:04 upper */
    {   795071983000LL,  69140, -1, 10, 1010,     -1500LL,  350,    2645000LL,
        2623242LL,   231476484, -1046964011,   -56625987,   4324,   -7753,   2624419LL,  18000,   -12 }, /* 2025-03-12 17:19:43 upper */
    {   795082098000LL,  69140, +1, 10, 1010,     -1500LL,  350,    1807300LL,
        1817088LL,  -531060141,  -931551183,   -55758625,   4324,   -7753,   1815088LL,  23088,   +20 }, /* 2025-03-12 20:08:18 lower */
    {   795094357000LL,  69140, +1, 10, 1010,     -1500LL,  350,    1207500LL,
        1216350LL, -1058476839,  -171909836,   -54729272,  -1883,  -10117,   1214072LL,  27392,   +23 }, /* 2025-03-12 23:32:37 lower */
    {   795113685000LL,  69140, +1, 10, 1010,     -1500LL,  350,    1230000LL,
        1238898LL,  -343407535,  1015960916,   -53067759,   4542,   16503,   1241024LL,  24272,   -21 }, /* 2025-03-13 04:54:45 lower */
};

#define INTERCEPT_ROW_COUNT (sizeof intercept_rows / sizeof intercept_rows[0])
