/* Out-of-tree hardware test harness for astro-nav-int's embedded profiles.
 * Runs profile_run() (the "all" profile: every public entry point at least
 * once) on the target MCU and prints a structured result record over serial,
 * repeating so a late attach still sees it.
 *
 * build_info.h (repo commit stamp) and profile_pin.h (expected hash, computed
 * by a HOST run of the same profile TU at prepare time) are both generated by
 * prepare.sh — this file hardcodes neither. HW_TEST_TARGET comes from
 * platformio.ini; the arch string is derived from compiler macros, so the
 * transcript itself proves which instruction set the binary was built for.
 */
#include <Arduino.h>
#include <stdint.h>
#include "build_info.h"
#include "profile_pin.h"

#ifndef HW_TEST_TARGET
#error "HW_TEST_TARGET must be defined in platformio.ini build_flags"
#endif

#if defined(__riscv)
#define HW_ARCH "rv32"
#elif defined(__arm__) || defined(__ARM_ARCH)
#define HW_ARCH "arm"
#elif defined(__AVR__)
#define HW_ARCH "avr8"
#elif defined(__xtensa__) || defined(__XTENSA__)
#define HW_ARCH "xtensa"
#else
#define HW_ARCH "unknown"
#endif

extern "C" uint64_t profile_run(void);
extern "C" const char profile_name[];

static void print_hex64(uint64_t v)
{
    char buf[17];
    for (int i = 15; i >= 0; i--) { buf[i] = "0123456789abcdef"[v & 0xf]; v >>= 4; }
    buf[16] = 0;
    Serial.print(buf);
}

void setup()
{
    Serial.begin(115200);
}

void loop()
{
    uint32_t t0 = millis();
    uint64_t h = profile_run();
    uint32_t dt = millis() - t0;

    Serial.print("target " HW_TEST_TARGET " arch " HW_ARCH
                 " tree " BUILD_COMMIT " PROFILE ");
    Serial.print(profile_name);
    Serial.print(" hash ");
    print_hex64(h);
    Serial.print(" (");
    Serial.print(dt);
    Serial.println(" ms, informational)");
    if (h == PINNED_HASH) {
        Serial.println("profile: PASS (target reproduces the host-computed PROFILE hash)");
    } else {
        Serial.print("profile: FAIL - expected ");
        print_hex64(PINNED_HASH);
        Serial.println("");
    }
    delay(3000);
}
