#!/usr/bin/env python3
"""Generate ephemeris_reference.h: independent truth vectors for the
star almanac.

The repo's own oracle (--native-reference) validates the integer
arithmetic against a double-precision implementation of the SAME model
(IAU 1976 precession + ERA-based GMST, no nutation/aberration/proper
motion). This script generates truth rows from an INDEPENDENT,
authoritative model instead, so `sight_reduction --ephemeris-check`
measures the almanac's real-sky error, not its self-consistency:

  Hipparcos astrometry (proper motion, parallax) -> geocentric
  apparent place (annual aberration, gravitational light deflection,
  IAU 2000A/2006 precession-nutation) -> ITRS earth-fixed frame,
  via Skyfield + the JPL DE421 ephemeris.

This is a one-time OFFLINE generator: the repo commits its integer
output (ephemeris_reference.h) and never needs Python at build or
test time. Rerun only to change the sample schedule or the catalog.

  python3 -m venv venv
  venv/bin/pip install skyfield==1.54 pandas==3.0.3
  venv/bin/python tools/make_ephemeris_reference.py > ephemeris_reference.h

(The versions are the ones the committed header was generated with;
newer ones almost certainly reproduce it, but pin first, then bump
deliberately.) Downloads on first run (cached in
tools/skyfield-cache/): hip_main.dat (Hipparcos catalog) and de421.bsp
(JPL ephemeris). The generated header records the skyfield version and
the SHA-256 of both data files, so a regeneration that differs can be
traced to its inputs.
"""

import hashlib
import math
import sys
import skyfield
from skyfield.api import Loader, Star
from skyfield.data import hipparcos
from skyfield.framelib import itrs

# Catalog order must match astro_nav_stars[] in astro_nav.c.
STARS = [
    ("Sirius", 32349), ("Canopus", 30438), ("Arcturus", 69673),
    ("Vega", 91262), ("Capella", 24608), ("Rigel", 24436),
    ("Procyon", 37279), ("Betelgeuse", 27989), ("Achernar", 7588),
    ("Altair", 97649), ("Aldebaran", 21421), ("Spica", 65474),
    ("Antares", 80763), ("Pollux", 37826), ("Fomalhaut", 113368),
    ("Deneb", 102098), ("Regulus", 49669), ("Polaris", 11767),
]

# UT1 ms since J2000.0 (2000-01-01 12:00:00 UT1). 15 epochs spanning
# 2000..2036, deliberately NOT round multiples of anything, so GMST
# fractional terms and the Q16.48 century conversion get exercised.
EPOCHS_MS = [n * 81_240_000_000 + 12_345_678 for n in range(15)]

# Sun epochs: the Sun's error is periodic in the year (equation-of-
# center residuals), so sample it densely across annual phase: a step
# of ~315.6 days walks the season backwards ~50 days per row, covering
# the full cycle several times over 2000-2035. 41 rows, plus the
# distance extremes sampled explicitly -- perihelion and aphelion are
# where SD/HP truth is most sensitive to the distance model.
SUN_EPOCHS_MS = [n * 27_270_000_000 + 9_876_543 for n in range(41)] + [
    820_731_600_000,     # 2026-01-03 17:00 UT1, perihelion
    836_629_200_000,     # 2026-07-06 17:00 UT1, aphelion
    1_104_670_800_000,   # 2035-01-03 01:00 UT1, perihelion
    1_120_636_800_000,   # 2035-07-06 20:00 UT1, aphelion
]

# Moon epochs: the Moon's error is periodic on the anomalistic and
# synodic months, not the year, so the cadence must walk LUNAR phase:
# ~322.6-day steps advance 0.71 anomalistic / 0.92 synodic cycles per
# row, covering both several times over 2000-2035 (and ~1.9 nodal
# cycles). Plus the targeted extremes: the 2026 extreme perigee/apogee
# pair (the distance extremes, where SD/HP truth is most sensitive --
# the same instants the Makefile pins), the 2025 major-standstill
# declination extremes, and one crossing of each node (beta = 0).
MOON_EPOCHS_MS = [n * 27_870_000_000 + 7_654_321 for n in range(41)] + [
    850_244_400_000,     # 2026-12-11 06:00 UT1, apogee, 406436 km
    851_374_800_000,     # 2026-12-24 08:00 UT1, perigee, 356648 km
    794_635_200_000,     # 2025-03-07 16:00 UT1, standstill, dec +28.72
    795_898_800_000,     # 2025-03-22 07:00 UT1, standstill, dec -28.72
    836_424_000_000,     # 2026-07-04 08:00 UT1, ascending node
    835_164_000_000,     # 2026-06-19 18:00 UT1, descending node
]

J2000_JD = 2451545.0
MS_PER_DAY = 86_400_000.0
Q30 = 1 << 30
MARCMIN_PER_RAD = 180.0 * 60.0 * 1000.0 / math.pi


def q30(component):
    return int(round(component * Q30))


def sha256_of(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main():
    load = Loader("tools/skyfield-cache")
    ts = load.timescale()
    eph = load("de421.bsp")
    earth = eph["earth"]
    with load.open(hipparcos.URL) as f:
        df = hipparcos.load_dataframe(f)

    print("/* Generated by tools/make_ephemeris_reference.py"
          " -- do not edit.")
    print(" *")
    print(" * Independent truth vectors for the star almanac:"
          " apparent star")
    print(" * directions in the earth-fixed (ITRS) frame from"
          " Skyfield/DE421")
    print(" * (Hipparcos astrometry incl. proper motion, annual"
          " aberration,")
    print(" * light deflection, IAU 2000A/2006 precession-nutation),")
    print(" * sampled 2000-2036. Q2.30 unit vectors, same convention"
          " as")
    print(" * astro_nav_celestial_to_earthfixed() output."
          " Consumed by")
    print(" * `sight_reduction --ephemeris-check`.")
    print(" *")
    print(" * The Sun section below covers the Sun almanac the same"
          " way: apparent")
    print(" * direction plus distance (micro-AU) at 45 epochs -- a"
          " ~315.6-day")
    print(" * cadence walking the annual error cycle over 2000-2035,"
          " plus the")
    print(" * 2026/2035 perihelion and aphelion -- each row carrying"
          " Skyfield's")
    print(" * TT - UT1 so the caller-supplied time contract is"
          " exercised.")
    print(" *")
    print(" * The Moon section samples a ~322.6-day cadence that"
          " walks the")
    print(" * anomalistic and synodic phases (the Moon's error"
          " periods, not")
    print(" * the year's) across 2000-2035, plus the 2026 extreme")
    print(" * perigee/apogee pair, the 2025 major-standstill"
          " declination")
    print(" * extremes, and one crossing of each node. Rows carry"
          " TT - UT1")
    print(" * and truth geometric distance/SD/HP -- SD and HP as full")
    print(" * arcsines of the DE421 distance, because at the Moon's"
          " 54-61'")
    print(" * parallax the small-angle ratio the Sun rows use is a few")
    print(" * milli-arcmin off.")
    print(" *")
    print(" * Provenance (see tools/make_ephemeris_reference.py):")
    print(" *   skyfield %s" % skyfield.__version__)
    print(" *   de421.bsp sha256")
    print(" *     %s" % sha256_of("tools/skyfield-cache/de421.bsp"))
    print(" *   hip_main.dat sha256")
    print(" *     %s */" % sha256_of("tools/skyfield-cache/hip_main.dat"))
    print()
    print("typedef struct {")
    print("    int32_t star;    /* index into astro_nav_stars[] */")
    print("    int64_t ut1_ms;  /* UT1 ms since J2000.0 */")
    print("    int32_t x, y, z; /* ITRS apparent direction, Q2.30 */")
    print("} ephem_ref_row_t;")
    print()
    print("static const ephem_ref_row_t ephem_ref_rows[] = {")

    for ms in EPOCHS_MS:
        t = ts.ut1_jd(J2000_JD + ms / MS_PER_DAY)
        for index, (name, hip) in enumerate(STARS):
            star = Star.from_dataframe(df.loc[hip])
            apparent = earth.at(t).observe(star).apparent()
            x, y, z = apparent.frame_xyz(itrs).au
            norm = (x * x + y * y + z * z) ** 0.5
            print("    { %2d, %13dLL, %11d, %11d, %11d }, /* %-10s */"
                  % (index, ms, q30(x / norm), q30(y / norm),
                     q30(z / norm), name))

    print("};")
    print()
    print("#define EPHEM_REF_ROW_COUNT "
          "(sizeof ephem_ref_rows / sizeof ephem_ref_rows[0])")

    # Sun rows. The instant is set in UT1 (rotation's timescale);
    # Skyfield's delta-T model supplies the matching TT, and the row
    # carries TT - UT1 so the checker exercises the caller-supplied
    # time contract of astro_nav_sun_earthfixed().
    sun = eph["sun"]
    print()
    print("typedef struct {")
    print("    int64_t ut1_ms;          /* UT1 ms since J2000.0 */")
    print("    int32_t tt_minus_ut1_ms; /* Skyfield's delta-T"
          " at that instant */")
    print("    int32_t x, y, z;         /* ITRS apparent direction,"
          " Q2.30 */")
    print("    int32_t dist_uau;        /* apparent distance,"
          " micro-AU */")
    print("} ephem_sun_row_t;")
    print()
    print("static const ephem_sun_row_t ephem_sun_rows[] = {")
    for ms in SUN_EPOCHS_MS:
        t = ts.ut1_jd(J2000_JD + ms / MS_PER_DAY)
        ttmut1 = int(round((t.tt - t.ut1) * MS_PER_DAY))
        apparent = earth.at(t).observe(sun).apparent()
        x, y, z = apparent.frame_xyz(itrs).au
        norm = (x * x + y * y + z * z) ** 0.5
        print("    { %13dLL, %6d, %11d, %11d, %11d, %7d },"
              % (ms, ttmut1, q30(x / norm), q30(y / norm),
                 q30(z / norm), int(round(norm * 1e6))))
    print("};")
    print()
    print("#define EPHEM_SUN_ROW_COUNT "
          "(sizeof ephem_sun_rows / sizeof ephem_sun_rows[0])")

    # Moon rows: same construction as the Sun's, plus truth SD/HP
    # columns. The Sun checker derives truth SD/HP from the distance
    # by small-angle division in C; at the Moon's 54-61' parallax the
    # arcsine's cubic term is a few milli-arcmin, so the full-precision
    # arcsine happens HERE and the checker compares angles directly.
    # Radii match the library's constants: 6378.137 km equatorial
    # Earth, 1737.4 km Moon.
    #
    # Distance is GEOMETRIC ((moon - earth).at(t)), not the light-time
    # retarded range .observe() reports: the Earth-Moon pair moves at
    # ~30 km/s barycentrically, so retarding the Moon by the ~1.28 s
    # light time shifts the reported range by up to ~38 km with lunar
    # phase -- while direction is barely touched (the shared velocity
    # cancels against aberration, the ~0.01' net the header quantifies).
    # Meeus's Delta and the almanac's HP = arcsin(6378.137/Delta) are
    # instantaneous geometry, so geometric is the matching truth.
    moon = eph["moon"]
    moon_geom = moon - earth
    print()
    print("typedef struct {")
    print("    int64_t ut1_ms;          /* UT1 ms since J2000.0 */")
    print("    int32_t tt_minus_ut1_ms; /* Skyfield's delta-T"
          " at that instant */")
    print("    int32_t x, y, z;         /* ITRS apparent direction,"
          " Q2.30 */")
    print("    int32_t dist_km;         /* geometric distance, km */")
    print("    int32_t sd_marcmin;      /* asin(1737.4 km / dist) */")
    print("    int32_t hp_marcmin;      /* asin(6378.137 km / dist)"
          " */")
    print("} ephem_moon_row_t;")
    print()
    print("static const ephem_moon_row_t ephem_moon_rows[] = {")
    for ms in MOON_EPOCHS_MS:
        t = ts.ut1_jd(J2000_JD + ms / MS_PER_DAY)
        ttmut1 = int(round((t.tt - t.ut1) * MS_PER_DAY))
        apparent = earth.at(t).observe(moon).apparent()
        x, y, z = apparent.frame_xyz(itrs).au
        norm = (x * x + y * y + z * z) ** 0.5
        km = moon_geom.at(t).distance().km
        sd = int(round(math.asin(1737.4 / km) * MARCMIN_PER_RAD))
        hp = int(round(math.asin(6378.137 / km) * MARCMIN_PER_RAD))
        print("    { %13dLL, %6d, %11d, %11d, %11d, %6d, %5d, %5d },"
              % (ms, ttmut1, q30(x / norm), q30(y / norm),
                 q30(z / norm), int(round(km)), sd, hp))
    print("};")
    print()
    print("#define EPHEM_MOON_ROW_COUNT "
          "(sizeof ephem_moon_rows / sizeof ephem_moon_rows[0])")
    return 0


if __name__ == "__main__":
    sys.exit(main())
